package ui.controllers;

import database.DatabaseConnection;
import database.tables.Game;
import database.tables.Team;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import stats.RecordsBreakdown;
import stats.Records;
import ui.Launcher;

import java.net.URL;
import java.sql.SQLException;
import java.util.*;

public class RecordsController implements Initializable {
    @FXML private Label team1_name;
    @FXML private Label team2_name;
    @FXML private TextField singleGame_t1_record_max_runs;
    @FXML private TextField singleGame_t1_count_max_runs;
    @FXML private TextField singleGame_t1_dates_max_runs;
    @FXML private TextField singleGame_t1_record_max_plateAppearances;
    @FXML private TextField singleGame_t1_count_max_plateAppearances;
    @FXML private TextField singleGame_t1_dates_max_plateAppearances;
    @FXML private TextField singleGame_t1_record_max_atBats;
    @FXML private TextField singleGame_t1_count_max_atBats;
    @FXML private TextField singleGame_t1_dates_max_atBats;
    @FXML private TextField singleGame_t1_record_max_walks;
    @FXML private TextField singleGame_t1_count_max_walks;
    @FXML private TextField singleGame_t1_dates_max_walks;
    @FXML private TextField singleGame_t1_record_max_strikeouts;
    @FXML private TextField singleGame_t1_count_max_strikeouts;
    @FXML private TextField singleGame_t1_dates_max_strikeouts;
    @FXML private TextField singleGame_t1_record_max_fieldouts;
    @FXML private TextField singleGame_t1_count_max_fieldouts;
    @FXML private TextField singleGame_t1_dates_max_fieldouts;
    @FXML private TextField singleGame_t1_record_max_hits;
    @FXML private TextField singleGame_t1_count_max_hits;
    @FXML private TextField singleGame_t1_dates_max_hits;
    @FXML private TextField singleGame_t1_record_max_singles;
    @FXML private TextField singleGame_t1_count_max_singles;
    @FXML private TextField singleGame_t1_dates_max_singles;
    @FXML private TextField singleGame_t1_record_max_doubles;
    @FXML private TextField singleGame_t1_count_max_doubles;
    @FXML private TextField singleGame_t1_dates_max_doubles;
    @FXML private TextField singleGame_t1_record_max_triples;
    @FXML private TextField singleGame_t1_count_max_triples;
    @FXML private TextField singleGame_t1_dates_max_triples;
    @FXML private TextField singleGame_t1_record_max_homeruns;
    @FXML private TextField singleGame_t1_count_max_homeruns;
    @FXML private TextField singleGame_t1_dates_max_homeruns;
    @FXML private TextField singleGame_t2_record_max_runs;
    @FXML private TextField singleGame_t2_count_max_runs;
    @FXML private TextField singleGame_t2_dates_max_runs;
    @FXML private TextField singleGame_t2_record_max_plateAppearances;
    @FXML private TextField singleGame_t2_count_max_plateAppearances;
    @FXML private TextField singleGame_t2_dates_max_plateAppearances;
    @FXML private TextField singleGame_t2_record_max_atBats;
    @FXML private TextField singleGame_t2_count_max_atBats;
    @FXML private TextField singleGame_t2_dates_max_atBats;
    @FXML private TextField singleGame_t2_record_max_walks;
    @FXML private TextField singleGame_t2_count_max_walks;
    @FXML private TextField singleGame_t2_dates_max_walks;
    @FXML private TextField singleGame_t2_record_max_strikeouts;
    @FXML private TextField singleGame_t2_count_max_strikeouts;
    @FXML private TextField singleGame_t2_dates_max_strikeouts;
    @FXML private TextField singleGame_t2_record_max_fieldouts;
    @FXML private TextField singleGame_t2_count_max_fieldouts;
    @FXML private TextField singleGame_t2_dates_max_fieldouts;
    @FXML private TextField singleGame_t2_record_max_hits;
    @FXML private TextField singleGame_t2_count_max_hits;
    @FXML private TextField singleGame_t2_dates_max_hits;
    @FXML private TextField singleGame_t2_record_max_singles;
    @FXML private TextField singleGame_t2_count_max_singles;
    @FXML private TextField singleGame_t2_dates_max_singles;
    @FXML private TextField singleGame_t2_record_max_doubles;
    @FXML private TextField singleGame_t2_count_max_doubles;
    @FXML private TextField singleGame_t2_dates_max_doubles;
    @FXML private TextField singleGame_t2_record_max_triples;
    @FXML private TextField singleGame_t2_count_max_triples;
    @FXML private TextField singleGame_t2_dates_max_triples;
    @FXML private TextField singleGame_t2_record_max_homeruns;
    @FXML private TextField singleGame_t2_count_max_homeruns;
    @FXML private TextField singleGame_t2_dates_max_homeruns;
    @FXML private TextField singleGame_t1_record_min_runs;
    @FXML private TextField singleGame_t1_count_min_runs;
    @FXML private TextField singleGame_t1_dates_min_runs;
    @FXML private TextField singleGame_t1_record_min_plateAppearances;
    @FXML private TextField singleGame_t1_count_min_plateAppearances;
    @FXML private TextField singleGame_t1_dates_min_plateAppearances;
    @FXML private TextField singleGame_t1_record_min_atBats;
    @FXML private TextField singleGame_t1_count_min_atBats;
    @FXML private TextField singleGame_t1_dates_min_atBats;
    @FXML private TextField singleGame_t1_record_min_walks;
    @FXML private TextField singleGame_t1_count_min_walks;
    @FXML private TextField singleGame_t1_dates_min_walks;
    @FXML private TextField singleGame_t1_record_min_strikeouts;
    @FXML private TextField singleGame_t1_count_min_strikeouts;
    @FXML private TextField singleGame_t1_dates_min_strikeouts;
    @FXML private TextField singleGame_t1_record_min_fieldouts;
    @FXML private TextField singleGame_t1_count_min_fieldouts;
    @FXML private TextField singleGame_t1_dates_min_fieldouts;
    @FXML private TextField singleGame_t1_record_min_hits;
    @FXML private TextField singleGame_t1_count_min_hits;
    @FXML private TextField singleGame_t1_dates_min_hits;
    @FXML private TextField singleGame_t1_record_min_singles;
    @FXML private TextField singleGame_t1_count_min_singles;
    @FXML private TextField singleGame_t1_dates_min_singles;
    @FXML private TextField singleGame_t1_record_min_doubles;
    @FXML private TextField singleGame_t1_count_min_doubles;
    @FXML private TextField singleGame_t1_dates_min_doubles;
    @FXML private TextField singleGame_t1_record_min_triples;
    @FXML private TextField singleGame_t1_count_min_triples;
    @FXML private TextField singleGame_t1_dates_min_triples;
    @FXML private TextField singleGame_t1_record_min_homeruns;
    @FXML private TextField singleGame_t1_count_min_homeruns;
    @FXML private TextField singleGame_t1_dates_min_homeruns;
    @FXML private TextField singleGame_t2_record_min_runs;
    @FXML private TextField singleGame_t2_count_min_runs;
    @FXML private TextField singleGame_t2_dates_min_runs;
    @FXML private TextField singleGame_t2_record_min_plateAppearances;
    @FXML private TextField singleGame_t2_count_min_plateAppearances;
    @FXML private TextField singleGame_t2_dates_min_plateAppearances;
    @FXML private TextField singleGame_t2_record_min_atBats;
    @FXML private TextField singleGame_t2_count_min_atBats;
    @FXML private TextField singleGame_t2_dates_min_atBats;
    @FXML private TextField singleGame_t2_record_min_walks;
    @FXML private TextField singleGame_t2_count_min_walks;
    @FXML private TextField singleGame_t2_dates_min_walks;
    @FXML private TextField singleGame_t2_record_min_strikeouts;
    @FXML private TextField singleGame_t2_count_min_strikeouts;
    @FXML private TextField singleGame_t2_dates_min_strikeouts;
    @FXML private TextField singleGame_t2_record_min_fieldouts;
    @FXML private TextField singleGame_t2_count_min_fieldouts;
    @FXML private TextField singleGame_t2_dates_min_fieldouts;
    @FXML private TextField singleGame_t2_record_min_hits;
    @FXML private TextField singleGame_t2_count_min_hits;
    @FXML private TextField singleGame_t2_dates_min_hits;
    @FXML private TextField singleGame_t2_record_min_singles;
    @FXML private TextField singleGame_t2_count_min_singles;
    @FXML private TextField singleGame_t2_dates_min_singles;
    @FXML private TextField singleGame_t2_record_min_doubles;
    @FXML private TextField singleGame_t2_count_min_doubles;
    @FXML private TextField singleGame_t2_dates_min_doubles;
    @FXML private TextField singleGame_t2_record_min_triples;
    @FXML private TextField singleGame_t2_count_min_triples;
    @FXML private TextField singleGame_t2_dates_min_triples;
    @FXML private TextField singleGame_t2_record_min_homeruns;
    @FXML private TextField singleGame_t2_count_min_homeruns;
    @FXML private TextField singleGame_t2_dates_min_homeruns;
    @FXML private TextField singleInning_t1_record_max_runs;
    @FXML private TextField singleInning_t1_count_max_runs;
    @FXML private TextField singleInning_t1_dates_max_runs;
    @FXML private TextField singleInning_t1_record_max_plateAppearances;
    @FXML private TextField singleInning_t1_count_max_plateAppearances;
    @FXML private TextField singleInning_t1_dates_max_plateAppearances;
    @FXML private TextField singleInning_t1_record_max_atBats;
    @FXML private TextField singleInning_t1_count_max_atBats;
    @FXML private TextField singleInning_t1_dates_max_atBats;
    @FXML private TextField singleInning_t1_record_max_walks;
    @FXML private TextField singleInning_t1_count_max_walks;
    @FXML private TextField singleInning_t1_dates_max_walks;
    @FXML private TextField singleInning_t1_record_max_strikeouts;
    @FXML private TextField singleInning_t1_count_max_strikeouts;
    @FXML private TextField singleInning_t1_dates_max_strikeouts;
    @FXML private TextField singleInning_t1_record_max_fieldouts;
    @FXML private TextField singleInning_t1_count_max_fieldouts;
    @FXML private TextField singleInning_t1_dates_max_fieldouts;
    @FXML private TextField singleInning_t1_record_max_hits;
    @FXML private TextField singleInning_t1_count_max_hits;
    @FXML private TextField singleInning_t1_dates_max_hits;
    @FXML private TextField singleInning_t1_record_max_singles;
    @FXML private TextField singleInning_t1_count_max_singles;
    @FXML private TextField singleInning_t1_dates_max_singles;
    @FXML private TextField singleInning_t1_record_max_doubles;
    @FXML private TextField singleInning_t1_count_max_doubles;
    @FXML private TextField singleInning_t1_dates_max_doubles;
    @FXML private TextField singleInning_t1_record_max_triples;
    @FXML private TextField singleInning_t1_count_max_triples;
    @FXML private TextField singleInning_t1_dates_max_triples;
    @FXML private TextField singleInning_t1_record_max_homeruns;
    @FXML private TextField singleInning_t1_count_max_homeruns;
    @FXML private TextField singleInning_t1_dates_max_homeruns;
    @FXML private TextField singleInning_t2_record_max_runs;
    @FXML private TextField singleInning_t2_count_max_runs;
    @FXML private TextField singleInning_t2_dates_max_runs;
    @FXML private TextField singleInning_t2_record_max_plateAppearances;
    @FXML private TextField singleInning_t2_count_max_plateAppearances;
    @FXML private TextField singleInning_t2_dates_max_plateAppearances;
    @FXML private TextField singleInning_t2_record_max_atBats;
    @FXML private TextField singleInning_t2_count_max_atBats;
    @FXML private TextField singleInning_t2_dates_max_atBats;
    @FXML private TextField singleInning_t2_record_max_walks;
    @FXML private TextField singleInning_t2_count_max_walks;
    @FXML private TextField singleInning_t2_dates_max_walks;
    @FXML private TextField singleInning_t2_record_max_strikeouts;
    @FXML private TextField singleInning_t2_count_max_strikeouts;
    @FXML private TextField singleInning_t2_dates_max_strikeouts;
    @FXML private TextField singleInning_t2_record_max_fieldouts;
    @FXML private TextField singleInning_t2_count_max_fieldouts;
    @FXML private TextField singleInning_t2_dates_max_fieldouts;
    @FXML private TextField singleInning_t2_record_max_hits;
    @FXML private TextField singleInning_t2_count_max_hits;
    @FXML private TextField singleInning_t2_dates_max_hits;
    @FXML private TextField singleInning_t2_record_max_singles;
    @FXML private TextField singleInning_t2_count_max_singles;
    @FXML private TextField singleInning_t2_dates_max_singles;
    @FXML private TextField singleInning_t2_record_max_doubles;
    @FXML private TextField singleInning_t2_count_max_doubles;
    @FXML private TextField singleInning_t2_dates_max_doubles;
    @FXML private TextField singleInning_t2_record_max_triples;
    @FXML private TextField singleInning_t2_count_max_triples;
    @FXML private TextField singleInning_t2_dates_max_triples;
    @FXML private TextField singleInning_t2_record_max_homeruns;
    @FXML private TextField singleInning_t2_count_max_homeruns;
    @FXML private TextField singleInning_t2_dates_max_homeruns;
    @FXML private TextField singleInning_t1_record_min_runs;
    @FXML private TextField singleInning_t1_count_min_runs;
    @FXML private TextField singleInning_t1_dates_min_runs;
    @FXML private TextField singleInning_t1_record_min_plateAppearances;
    @FXML private TextField singleInning_t1_count_min_plateAppearances;
    @FXML private TextField singleInning_t1_dates_min_plateAppearances;
    @FXML private TextField singleInning_t1_record_min_atBats;
    @FXML private TextField singleInning_t1_count_min_atBats;
    @FXML private TextField singleInning_t1_dates_min_atBats;
    @FXML private TextField singleInning_t1_record_min_walks;
    @FXML private TextField singleInning_t1_count_min_walks;
    @FXML private TextField singleInning_t1_dates_min_walks;
    @FXML private TextField singleInning_t1_record_min_strikeouts;
    @FXML private TextField singleInning_t1_count_min_strikeouts;
    @FXML private TextField singleInning_t1_dates_min_strikeouts;
    @FXML private TextField singleInning_t1_record_min_fieldouts;
    @FXML private TextField singleInning_t1_count_min_fieldouts;
    @FXML private TextField singleInning_t1_dates_min_fieldouts;
    @FXML private TextField singleInning_t1_record_min_hits;
    @FXML private TextField singleInning_t1_count_min_hits;
    @FXML private TextField singleInning_t1_dates_min_hits;
    @FXML private TextField singleInning_t1_record_min_singles;
    @FXML private TextField singleInning_t1_count_min_singles;
    @FXML private TextField singleInning_t1_dates_min_singles;
    @FXML private TextField singleInning_t1_record_min_doubles;
    @FXML private TextField singleInning_t1_count_min_doubles;
    @FXML private TextField singleInning_t1_dates_min_doubles;
    @FXML private TextField singleInning_t1_record_min_triples;
    @FXML private TextField singleInning_t1_count_min_triples;
    @FXML private TextField singleInning_t1_dates_min_triples;
    @FXML private TextField singleInning_t1_record_min_homeruns;
    @FXML private TextField singleInning_t1_count_min_homeruns;
    @FXML private TextField singleInning_t1_dates_min_homeruns;
    @FXML private TextField singleInning_t2_record_min_runs;
    @FXML private TextField singleInning_t2_count_min_runs;
    @FXML private TextField singleInning_t2_dates_min_runs;
    @FXML private TextField singleInning_t2_record_min_plateAppearances;
    @FXML private TextField singleInning_t2_count_min_plateAppearances;
    @FXML private TextField singleInning_t2_dates_min_plateAppearances;
    @FXML private TextField singleInning_t2_record_min_atBats;
    @FXML private TextField singleInning_t2_count_min_atBats;
    @FXML private TextField singleInning_t2_dates_min_atBats;
    @FXML private TextField singleInning_t2_record_min_walks;
    @FXML private TextField singleInning_t2_count_min_walks;
    @FXML private TextField singleInning_t2_dates_min_walks;
    @FXML private TextField singleInning_t2_record_min_strikeouts;
    @FXML private TextField singleInning_t2_count_min_strikeouts;
    @FXML private TextField singleInning_t2_dates_min_strikeouts;
    @FXML private TextField singleInning_t2_record_min_fieldouts;
    @FXML private TextField singleInning_t2_count_min_fieldouts;
    @FXML private TextField singleInning_t2_dates_min_fieldouts;
    @FXML private TextField singleInning_t2_record_min_hits;
    @FXML private TextField singleInning_t2_count_min_hits;
    @FXML private TextField singleInning_t2_dates_min_hits;
    @FXML private TextField singleInning_t2_record_min_singles;
    @FXML private TextField singleInning_t2_count_min_singles;
    @FXML private TextField singleInning_t2_dates_min_singles;
    @FXML private TextField singleInning_t2_record_min_doubles;
    @FXML private TextField singleInning_t2_count_min_doubles;
    @FXML private TextField singleInning_t2_dates_min_doubles;
    @FXML private TextField singleInning_t2_record_min_triples;
    @FXML private TextField singleInning_t2_count_min_triples;
    @FXML private TextField singleInning_t2_dates_min_triples;
    @FXML private TextField singleInning_t2_record_min_homeruns;
    @FXML private TextField singleInning_t2_count_min_homeruns;
    @FXML private TextField singleInning_t2_dates_min_homeruns;
    @FXML private Button back_button;

    private List<Game> gameList;
    private DatabaseConnection databaseConnection;
    private RecordsBreakdown t1RecordsBreakdown;
    private RecordsBreakdown t2RecordsBreakdown;

    public RecordsController()
    {
        databaseConnection = Launcher.databaseConnection;
    }

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        try {
            gameList = databaseConnection.getGameList();

            for(Team team : databaseConnection.getTeamList())
            {
                if(team.getTeam_name().equalsIgnoreCase(team1_name.getText()))
                    t1RecordsBreakdown = new RecordsBreakdown(team.getId());
                else if(team.getTeam_name().equalsIgnoreCase(team2_name.getText()))
                    t2RecordsBreakdown = new RecordsBreakdown(team.getId());
            }
            t1RecordsBreakdown.calculate();
            t2RecordsBreakdown.calculate();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        fillSingleGameRecords();
        fillSingleInningRecords();
    }

    private void fillSingleGameRecords()
    {
        /* team 1 max */
        Records t1SingleGameRecords = t1RecordsBreakdown.getSingleGameRecords();
        singleGame_t1_record_max_runs.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalRuns()));
        singleGame_t1_count_max_runs.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalRuns()));
        singleGame_t1_dates_max_runs.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalRuns()));
        singleGame_t1_record_max_plateAppearances.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalPlateAppearances()));
        singleGame_t1_count_max_plateAppearances.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalPlateAppearances()));
        singleGame_t1_dates_max_plateAppearances.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalPlateAppearances()));
        singleGame_t1_record_max_atBats.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalAtBats()));
        singleGame_t1_count_max_atBats.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalAtBats()));
        singleGame_t1_dates_max_atBats.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalAtBats()));
        singleGame_t1_record_max_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalWalks()));
        singleGame_t1_count_max_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalWalks()));
        singleGame_t1_dates_max_walks.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalWalks()));
        singleGame_t1_record_max_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalWalks()));
        singleGame_t1_count_max_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalWalks()));
        singleGame_t1_dates_max_walks.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalWalks()));
        singleGame_t1_record_max_strikeouts.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalStrikeouts()));
        singleGame_t1_count_max_strikeouts.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalStrikeouts()));
        singleGame_t1_dates_max_strikeouts.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalStrikeouts()));
        singleGame_t1_record_max_fieldouts.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalFieldouts()));
        singleGame_t1_count_max_fieldouts.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalFieldouts()));
        singleGame_t1_dates_max_fieldouts.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalFieldouts()));
        singleGame_t1_record_max_hits.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalHits()));
        singleGame_t1_count_max_hits.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalHits()));
        singleGame_t1_dates_max_hits.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalHits()));
        singleGame_t1_record_max_singles.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalSingles()));
        singleGame_t1_count_max_singles.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalSingles()));
        singleGame_t1_dates_max_singles.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalSingles()));
        singleGame_t1_record_max_doubles.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalDoubles()));
        singleGame_t1_count_max_doubles.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalDoubles()));
        singleGame_t1_dates_max_doubles.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalDoubles()));
        singleGame_t1_record_max_triples.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalTriples()));
        singleGame_t1_count_max_triples.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalTriples()));
        singleGame_t1_dates_max_triples.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalTriples()));
        singleGame_t1_record_max_homeruns.textProperty().set(String.valueOf(t1SingleGameRecords.getMaxTotalHomeruns()));
        singleGame_t1_count_max_homeruns.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_maxTotalHomeruns()));
        singleGame_t1_dates_max_homeruns.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_maxTotalHomeruns()));
        /* team 1 min */
        singleGame_t1_record_min_runs.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalRuns()));
        singleGame_t1_count_min_runs.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalRuns()));
        singleGame_t1_dates_min_runs.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalRuns()));
        singleGame_t1_record_min_plateAppearances.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalPlateAppearances()));
        singleGame_t1_count_min_plateAppearances.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalPlateAppearances()));
        singleGame_t1_dates_min_plateAppearances.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalPlateAppearances()));
        singleGame_t1_record_min_atBats.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalAtBats()));
        singleGame_t1_count_min_atBats.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalAtBats()));
        singleGame_t1_dates_min_atBats.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalAtBats()));
        singleGame_t1_record_min_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalWalks()));
        singleGame_t1_count_min_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalWalks()));
        singleGame_t1_dates_min_walks.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalWalks()));
        singleGame_t1_record_min_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalWalks()));
        singleGame_t1_count_min_walks.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalWalks()));
        singleGame_t1_dates_min_walks.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalWalks()));
        singleGame_t1_record_min_strikeouts.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalStrikeouts()));
        singleGame_t1_count_min_strikeouts.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalStrikeouts()));
        singleGame_t1_dates_min_strikeouts.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalStrikeouts()));
        singleGame_t1_record_min_fieldouts.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalFieldouts()));
        singleGame_t1_count_min_fieldouts.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalFieldouts()));
        singleGame_t1_dates_min_fieldouts.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalFieldouts()));
        singleGame_t1_record_min_hits.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalHits()));
        singleGame_t1_count_min_hits.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalHits()));
        singleGame_t1_dates_min_hits.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalHits()));
        singleGame_t1_record_min_singles.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalSingles()));
        singleGame_t1_count_min_singles.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalSingles()));
        singleGame_t1_dates_min_singles.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalSingles()));
        singleGame_t1_record_min_doubles.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalDoubles()));
        singleGame_t1_count_min_doubles.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalDoubles()));
        singleGame_t1_dates_min_doubles.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalDoubles()));
        singleGame_t1_record_min_triples.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalTriples()));
        singleGame_t1_count_min_triples.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalTriples()));
        singleGame_t1_dates_min_triples.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalTriples()));
        singleGame_t1_record_min_homeruns.textProperty().set(String.valueOf(t1SingleGameRecords.getMinTotalHomeruns()));
        singleGame_t1_count_min_homeruns.textProperty().set(String.valueOf(t1SingleGameRecords.getCount_minTotalHomeruns()));
        singleGame_t1_dates_min_homeruns.textProperty().set(gameIdListToString(t1SingleGameRecords.getGameIdList_minTotalHomeruns()));
        
        /* team 2 max */
        Records t2SingleGameRecords = t2RecordsBreakdown.getSingleGameRecords();
        singleGame_t2_record_max_runs.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalRuns()));
        singleGame_t2_count_max_runs.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalRuns()));
        singleGame_t2_dates_max_runs.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalRuns()));
        singleGame_t2_record_max_plateAppearances.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalPlateAppearances()));
        singleGame_t2_count_max_plateAppearances.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalPlateAppearances()));
        singleGame_t2_dates_max_plateAppearances.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalPlateAppearances()));
        singleGame_t2_record_max_atBats.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalAtBats()));
        singleGame_t2_count_max_atBats.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalAtBats()));
        singleGame_t2_dates_max_atBats.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalAtBats()));
        singleGame_t2_record_max_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalWalks()));
        singleGame_t2_count_max_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalWalks()));
        singleGame_t2_dates_max_walks.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalWalks()));
        singleGame_t2_record_max_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalWalks()));
        singleGame_t2_count_max_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalWalks()));
        singleGame_t2_dates_max_walks.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalWalks()));
        singleGame_t2_record_max_strikeouts.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalStrikeouts()));
        singleGame_t2_count_max_strikeouts.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalStrikeouts()));
        singleGame_t2_dates_max_strikeouts.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalStrikeouts()));
        singleGame_t2_record_max_fieldouts.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalFieldouts()));
        singleGame_t2_count_max_fieldouts.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalFieldouts()));
        singleGame_t2_dates_max_fieldouts.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalFieldouts()));
        singleGame_t2_record_max_hits.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalHits()));
        singleGame_t2_count_max_hits.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalHits()));
        singleGame_t2_dates_max_hits.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalHits()));
        singleGame_t2_record_max_singles.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalSingles()));
        singleGame_t2_count_max_singles.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalSingles()));
        singleGame_t2_dates_max_singles.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalSingles()));
        singleGame_t2_record_max_doubles.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalDoubles()));
        singleGame_t2_count_max_doubles.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalDoubles()));
        singleGame_t2_dates_max_doubles.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalDoubles()));
        singleGame_t2_record_max_triples.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalTriples()));
        singleGame_t2_count_max_triples.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalTriples()));
        singleGame_t2_dates_max_triples.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalTriples()));
        singleGame_t2_record_max_homeruns.textProperty().set(String.valueOf(t2SingleGameRecords.getMaxTotalHomeruns()));
        singleGame_t2_count_max_homeruns.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_maxTotalHomeruns()));
        singleGame_t2_dates_max_homeruns.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_maxTotalHomeruns()));
        /* team 2 min */
        singleGame_t2_record_min_runs.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalRuns()));
        singleGame_t2_count_min_runs.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalRuns()));
        singleGame_t2_dates_min_runs.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalRuns()));
        singleGame_t2_record_min_plateAppearances.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalPlateAppearances()));
        singleGame_t2_count_min_plateAppearances.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalPlateAppearances()));
        singleGame_t2_dates_min_plateAppearances.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalPlateAppearances()));
        singleGame_t2_record_min_atBats.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalAtBats()));
        singleGame_t2_count_min_atBats.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalAtBats()));
        singleGame_t2_dates_min_atBats.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalAtBats()));
        singleGame_t2_record_min_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalWalks()));
        singleGame_t2_count_min_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalWalks()));
        singleGame_t2_dates_min_walks.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalWalks()));
        singleGame_t2_record_min_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalWalks()));
        singleGame_t2_count_min_walks.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalWalks()));
        singleGame_t2_dates_min_walks.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalWalks()));
        singleGame_t2_record_min_strikeouts.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalStrikeouts()));
        singleGame_t2_count_min_strikeouts.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalStrikeouts()));
        singleGame_t2_dates_min_strikeouts.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalStrikeouts()));
        singleGame_t2_record_min_fieldouts.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalFieldouts()));
        singleGame_t2_count_min_fieldouts.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalFieldouts()));
        singleGame_t2_dates_min_fieldouts.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalFieldouts()));
        singleGame_t2_record_min_hits.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalHits()));
        singleGame_t2_count_min_hits.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalHits()));
        singleGame_t2_dates_min_hits.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalHits()));
        singleGame_t2_record_min_singles.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalSingles()));
        singleGame_t2_count_min_singles.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalSingles()));
        singleGame_t2_dates_min_singles.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalSingles()));
        singleGame_t2_record_min_doubles.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalDoubles()));
        singleGame_t2_count_min_doubles.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalDoubles()));
        singleGame_t2_dates_min_doubles.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalDoubles()));
        singleGame_t2_record_min_triples.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalTriples()));
        singleGame_t2_count_min_triples.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalTriples()));
        singleGame_t2_dates_min_triples.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalTriples()));
        singleGame_t2_record_min_homeruns.textProperty().set(String.valueOf(t2SingleGameRecords.getMinTotalHomeruns()));
        singleGame_t2_count_min_homeruns.textProperty().set(String.valueOf(t2SingleGameRecords.getCount_minTotalHomeruns()));
        singleGame_t2_dates_min_homeruns.textProperty().set(gameIdListToString(t2SingleGameRecords.getGameIdList_minTotalHomeruns()));
    }

    private void fillSingleInningRecords()
    {
        /* team 1 max */
        Records t1SingleInningRecords = t1RecordsBreakdown.getSingleInningRecords();
        singleInning_t1_record_max_runs.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalRuns()));
        singleInning_t1_count_max_runs.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalRuns()));
        singleInning_t1_dates_max_runs.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalRuns()));
        singleInning_t1_record_max_plateAppearances.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalPlateAppearances()));
        singleInning_t1_count_max_plateAppearances.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalPlateAppearances()));
        singleInning_t1_dates_max_plateAppearances.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalPlateAppearances()));
        singleInning_t1_record_max_atBats.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalAtBats()));
        singleInning_t1_count_max_atBats.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalAtBats()));
        singleInning_t1_dates_max_atBats.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalAtBats()));
        singleInning_t1_record_max_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalWalks()));
        singleInning_t1_count_max_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalWalks()));
        singleInning_t1_dates_max_walks.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalWalks()));
        singleInning_t1_record_max_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalWalks()));
        singleInning_t1_count_max_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalWalks()));
        singleInning_t1_dates_max_walks.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalWalks()));
        singleInning_t1_record_max_strikeouts.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalStrikeouts()));
        singleInning_t1_count_max_strikeouts.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalStrikeouts()));
        singleInning_t1_dates_max_strikeouts.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalStrikeouts()));
        singleInning_t1_record_max_fieldouts.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalFieldouts()));
        singleInning_t1_count_max_fieldouts.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalFieldouts()));
        singleInning_t1_dates_max_fieldouts.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalFieldouts()));
        singleInning_t1_record_max_hits.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalHits()));
        singleInning_t1_count_max_hits.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalHits()));
        singleInning_t1_dates_max_hits.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalHits()));
        singleInning_t1_record_max_singles.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalSingles()));
        singleInning_t1_count_max_singles.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalSingles()));
        singleInning_t1_dates_max_singles.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalSingles()));
        singleInning_t1_record_max_doubles.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalDoubles()));
        singleInning_t1_count_max_doubles.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalDoubles()));
        singleInning_t1_dates_max_doubles.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalDoubles()));
        singleInning_t1_record_max_triples.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalTriples()));
        singleInning_t1_count_max_triples.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalTriples()));
        singleInning_t1_dates_max_triples.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalTriples()));
        singleInning_t1_record_max_homeruns.textProperty().set(String.valueOf(t1SingleInningRecords.getMaxTotalHomeruns()));
        singleInning_t1_count_max_homeruns.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_maxTotalHomeruns()));
        singleInning_t1_dates_max_homeruns.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_maxTotalHomeruns()));
        /* team 1 min */
        singleInning_t1_record_min_runs.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalRuns()));
        singleInning_t1_count_min_runs.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalRuns()));
        singleInning_t1_dates_min_runs.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalRuns()));
        singleInning_t1_record_min_plateAppearances.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalPlateAppearances()));
        singleInning_t1_count_min_plateAppearances.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalPlateAppearances()));
        singleInning_t1_dates_min_plateAppearances.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalPlateAppearances()));
        singleInning_t1_record_min_atBats.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalAtBats()));
        singleInning_t1_count_min_atBats.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalAtBats()));
        singleInning_t1_dates_min_atBats.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalAtBats()));
        singleInning_t1_record_min_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalWalks()));
        singleInning_t1_count_min_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalWalks()));
        singleInning_t1_dates_min_walks.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalWalks()));
        singleInning_t1_record_min_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalWalks()));
        singleInning_t1_count_min_walks.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalWalks()));
        singleInning_t1_dates_min_walks.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalWalks()));
        singleInning_t1_record_min_strikeouts.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalStrikeouts()));
        singleInning_t1_count_min_strikeouts.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalStrikeouts()));
        singleInning_t1_dates_min_strikeouts.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalStrikeouts()));
        singleInning_t1_record_min_fieldouts.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalFieldouts()));
        singleInning_t1_count_min_fieldouts.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalFieldouts()));
        singleInning_t1_dates_min_fieldouts.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalFieldouts()));
        singleInning_t1_record_min_hits.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalHits()));
        singleInning_t1_count_min_hits.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalHits()));
        singleInning_t1_dates_min_hits.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalHits()));
        singleInning_t1_record_min_singles.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalSingles()));
        singleInning_t1_count_min_singles.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalSingles()));
        singleInning_t1_dates_min_singles.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalSingles()));
        singleInning_t1_record_min_doubles.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalDoubles()));
        singleInning_t1_count_min_doubles.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalDoubles()));
        singleInning_t1_dates_min_doubles.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalDoubles()));
        singleInning_t1_record_min_triples.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalTriples()));
        singleInning_t1_count_min_triples.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalTriples()));
        singleInning_t1_dates_min_triples.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalTriples()));
        singleInning_t1_record_min_homeruns.textProperty().set(String.valueOf(t1SingleInningRecords.getMinTotalHomeruns()));
        singleInning_t1_count_min_homeruns.textProperty().set(String.valueOf(t1SingleInningRecords.getCount_minTotalHomeruns()));
        singleInning_t1_dates_min_homeruns.textProperty().set(gameIdListToString(t1SingleInningRecords.getGameIdList_minTotalHomeruns()));

        /* team 2 max */
        Records t2SingleInningRecords = t2RecordsBreakdown.getSingleInningRecords();
        singleInning_t2_record_max_runs.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalRuns()));
        singleInning_t2_count_max_runs.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalRuns()));
        singleInning_t2_dates_max_runs.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalRuns()));
        singleInning_t2_record_max_plateAppearances.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalPlateAppearances()));
        singleInning_t2_count_max_plateAppearances.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalPlateAppearances()));
        singleInning_t2_dates_max_plateAppearances.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalPlateAppearances()));
        singleInning_t2_record_max_atBats.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalAtBats()));
        singleInning_t2_count_max_atBats.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalAtBats()));
        singleInning_t2_dates_max_atBats.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalAtBats()));
        singleInning_t2_record_max_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalWalks()));
        singleInning_t2_count_max_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalWalks()));
        singleInning_t2_dates_max_walks.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalWalks()));
        singleInning_t2_record_max_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalWalks()));
        singleInning_t2_count_max_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalWalks()));
        singleInning_t2_dates_max_walks.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalWalks()));
        singleInning_t2_record_max_strikeouts.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalStrikeouts()));
        singleInning_t2_count_max_strikeouts.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalStrikeouts()));
        singleInning_t2_dates_max_strikeouts.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalStrikeouts()));
        singleInning_t2_record_max_fieldouts.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalFieldouts()));
        singleInning_t2_count_max_fieldouts.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalFieldouts()));
        singleInning_t2_dates_max_fieldouts.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalFieldouts()));
        singleInning_t2_record_max_hits.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalHits()));
        singleInning_t2_count_max_hits.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalHits()));
        singleInning_t2_dates_max_hits.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalHits()));
        singleInning_t2_record_max_singles.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalSingles()));
        singleInning_t2_count_max_singles.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalSingles()));
        singleInning_t2_dates_max_singles.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalSingles()));
        singleInning_t2_record_max_doubles.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalDoubles()));
        singleInning_t2_count_max_doubles.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalDoubles()));
        singleInning_t2_dates_max_doubles.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalDoubles()));
        singleInning_t2_record_max_triples.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalTriples()));
        singleInning_t2_count_max_triples.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalTriples()));
        singleInning_t2_dates_max_triples.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalTriples()));
        singleInning_t2_record_max_homeruns.textProperty().set(String.valueOf(t2SingleInningRecords.getMaxTotalHomeruns()));
        singleInning_t2_count_max_homeruns.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_maxTotalHomeruns()));
        singleInning_t2_dates_max_homeruns.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_maxTotalHomeruns()));
        /* team 2 min */
        singleInning_t2_record_min_runs.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalRuns()));
        singleInning_t2_count_min_runs.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalRuns()));
        singleInning_t2_dates_min_runs.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalRuns()));
        singleInning_t2_record_min_plateAppearances.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalPlateAppearances()));
        singleInning_t2_count_min_plateAppearances.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalPlateAppearances()));
        singleInning_t2_dates_min_plateAppearances.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalPlateAppearances()));
        singleInning_t2_record_min_atBats.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalAtBats()));
        singleInning_t2_count_min_atBats.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalAtBats()));
        singleInning_t2_dates_min_atBats.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalAtBats()));
        singleInning_t2_record_min_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalWalks()));
        singleInning_t2_count_min_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalWalks()));
        singleInning_t2_dates_min_walks.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalWalks()));
        singleInning_t2_record_min_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalWalks()));
        singleInning_t2_count_min_walks.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalWalks()));
        singleInning_t2_dates_min_walks.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalWalks()));
        singleInning_t2_record_min_strikeouts.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalStrikeouts()));
        singleInning_t2_count_min_strikeouts.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalStrikeouts()));
        singleInning_t2_dates_min_strikeouts.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalStrikeouts()));
        singleInning_t2_record_min_fieldouts.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalFieldouts()));
        singleInning_t2_count_min_fieldouts.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalFieldouts()));
        singleInning_t2_dates_min_fieldouts.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalFieldouts()));
        singleInning_t2_record_min_hits.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalHits()));
        singleInning_t2_count_min_hits.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalHits()));
        singleInning_t2_dates_min_hits.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalHits()));
        singleInning_t2_record_min_singles.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalSingles()));
        singleInning_t2_count_min_singles.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalSingles()));
        singleInning_t2_dates_min_singles.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalSingles()));
        singleInning_t2_record_min_doubles.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalDoubles()));
        singleInning_t2_count_min_doubles.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalDoubles()));
        singleInning_t2_dates_min_doubles.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalDoubles()));
        singleInning_t2_record_min_triples.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalTriples()));
        singleInning_t2_count_min_triples.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalTriples()));
        singleInning_t2_dates_min_triples.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalTriples()));
        singleInning_t2_record_min_homeruns.textProperty().set(String.valueOf(t2SingleInningRecords.getMinTotalHomeruns()));
        singleInning_t2_count_min_homeruns.textProperty().set(String.valueOf(t2SingleInningRecords.getCount_minTotalHomeruns()));
        singleInning_t2_dates_min_homeruns.textProperty().set(gameIdListToString(t2SingleInningRecords.getGameIdList_minTotalHomeruns()));
    }

    private String gameIdListToString(List<Integer> gameIdList)
    {
        List<Game> copyGameList = new ArrayList<>(gameList);
        StringJoiner joiner = new StringJoiner(", ");

        for(Integer gameId : gameIdList)
        {
            for (Iterator<Game> iterator = copyGameList.iterator(); iterator.hasNext(); ) {
                Game game = iterator.next();
                if (game.getId().equals(gameId)) {
                    joiner.add(game.getDate_of_game().toString());
                    iterator.remove();
                }
            }
        }
        return joiner.toString();
    }

    public void backButtonClicked(ActionEvent actionEvent) {
        Stage stage = (Stage) back_button.getScene().getWindow();
        stage.close();
        Launcher.stg.show();
    }
}
